/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace JSCRevisionsLib {
  export type VotingRulesStruct = {
    votingPeriod: PromiseOrValue<BigNumberish>;
    approvals: PromiseOrValue<BigNumberish>;
    quorumPercentage: PromiseOrValue<BigNumberish>;
    majority: PromiseOrValue<BigNumberish>;
    roles: PromiseOrValue<string>[];
  };

  export type VotingRulesStructOutput = [
    number,
    number,
    number,
    number,
    string[]
  ] & {
    votingPeriod: number;
    approvals: number;
    quorumPercentage: number;
    majority: number;
    roles: string[];
  };
}

export interface JSCRevisionsLibInterface extends utils.Interface {
  functions: {
    "checkVotingRules((uint16,uint16,uint8,uint8,string[]))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "checkVotingRules"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkVotingRules",
    values: [JSCRevisionsLib.VotingRulesStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkVotingRules",
    data: BytesLike
  ): Result;

  events: {};
}

export interface JSCRevisionsLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: JSCRevisionsLibInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkVotingRules(
      r: JSCRevisionsLib.VotingRulesStruct,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  checkVotingRules(
    r: JSCRevisionsLib.VotingRulesStruct,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkVotingRules(
      r: JSCRevisionsLib.VotingRulesStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkVotingRules(
      r: JSCRevisionsLib.VotingRulesStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkVotingRules(
      r: JSCRevisionsLib.VotingRulesStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
