version: 0.2

env:
  variables:
    NODE_ENV: development

cache:
  paths:
    - node_modules/**/*

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - cd jsc
      - yarn 
      - yarn hardhat compile
      - cd ..
      - cd frontend
      - yarn
      - rm -rf typechain-types
      - yarn typechain
      - cd ..
artifacts:
  files:
    - "**/*"
