/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { JSCConfigurableTest } from "./JSCConfigurableTest";
export type { JSCRevisionedTest } from "./JSCRevisionedTest";
export type { JSCTitleTokenReceiverTest } from "./JSCTitleTokenReceiverTest";
export type { JSCTitleTokenTest } from "./JSCTitleTokenTest";
