/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as production from "./production";
export type { production };
import type * as tests from "./tests";
export type { tests };
export type { IJSCCabinet } from "./IJSCCabinet";
export type { IJSCConfigurable } from "./IJSCConfigurable";
export type { IJSCFreezable } from "./IJSCFreezable";
export type { IJSCGovernor } from "./IJSCGovernor";
export type { IJSCJurisdiction } from "./IJSCJurisdiction";
export type { IJSCRevisioned } from "./IJSCRevisioned";
export type { IJSCTitleToken } from "./IJSCTitleToken";
